language: php

php:
  - 8.1

services:
  - mysql

before_install:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - php artisan migrate --force

script:
  - php artisan test
