language: php

php:
  - 8.2

services:
  - mysql

before_script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - php artisan migrate --force

script:
  - php artisan test

